// admin-dashboard/src/lib/components/socialLinks.svelte
<script lang="ts">
    import { onMount } from 'svelte';

    onMount(() => {
        // Create container first
        const container = document.createElement('div');
        container.className = 'bmc-btn-container';
        document.body.appendChild(container);

        // Then load the script
        const script = document.createElement('script');
        script.type = 'text/javascript';
        script.src = 'https://cdnjs.buymeacoffee.com/1.0.0/button.prod.min.js';
        script.setAttribute('data-name', 'bmc-button');
        script.setAttribute('data-slug', 'shrishesha4');
        script.setAttribute('data-color', '#FF5F5F');
        script.setAttribute('data-emoji', '');
        script.setAttribute('data-font', 'Lato');
        script.setAttribute('data-text', 'Buy me a coffee');
        script.setAttribute('data-outline-color', '#000000');
        script.setAttribute('data-font-color', '#ffffff');
        script.setAttribute('data-coffee-color', '#FFDD00');

        document.addEventListener('DOMContentLoaded', () => {
            document.head.appendChild(script);
        });
        
        script.onload = () => {
            setTimeout(() => {
                // @ts-ignore
                if (window.BmcButton) {
                    // @ts-ignore
                    window.BmcButton.init();
                }
            }, 100);
        };


        return () => {
            // Cleanup on component unmount
            container?.remove();
            script?.remove();
        };
    });
</script>

<div>
    <!-- <div class="fixed bottom-8 left-8 hidden flex-col gap-8 md:flex">
        <a
            href="https://github.com/shrishesha4"
            target="_blank"
            rel="noopener noreferrer"
            class="text-neutral-700 transition hover:text-neutral-900 dark:text-neutral-300 dark:hover:text-neutral-100"
        >
            <i class="fa-brands fa-github text-2xl"></i>
            <span class="sr-only">GitHub</span>
        </a>
        <a
            href="https://linkedin.com/in/shrishesha"
            target="_blank"
            rel="noopener noreferrer"
            class="text-neutral-700 transition hover:text-neutral-900 dark:text-neutral-300 dark:hover:text-neutral-100"
        >
            <i class="fa-brands fa-linkedin text-2xl"></i>
            <span class="sr-only">LinkedIn</span>
        </a>
        <a
            href="https://x.com/Shrishesha4"
            target="_blank"
            rel="noopener noreferrer"
            class="text-neutral-700 transition hover:text-neutral-900 dark:text-neutral-300 dark:hover:text-neutral-100"
        >
            <i class="fa-brands fa-x-twitter text-2xl"></i>
            <span class="sr-only">Twitter</span>
        </a>
        <a
            href="mailto:shrisheshanarmatesshvara@gmail.com"
            target="_blank"
            class="text-neutral-700 transition hover:text-neutral-900 dark:text-neutral-300 dark:hover:text-neutral-100"
        >
            <i class="fa-regular fa-envelope text-2xl"></i>
            <span class="sr-only">Email</span>
        </a>
    </div> -->

    <!-- Add mobile view social links -->
    <div class="mb-3 flex justify-center gap-8 md:hidden">
        <!-- Same social links as above -->
        <a
            href="https://github.com/shrishesha4"
            target="_blank"
            rel="noopener noreferrer"
            class="text-neutral-700 transition hover:text-neutral-900 dark:text-neutral-300 dark:hover:text-neutral-100"
        >
            <i class="fa-brands fa-github text-2xl"></i>
            <span class="sr-only">GitHub</span>
        </a>
        <a
            href="https://linkedin.com/in/shrishesha"
            target="_blank"
            rel="noopener noreferrer"
            class="text-neutral-700 transition hover:text-neutral-900 dark:text-neutral-300 dark:hover:text-neutral-100"
        >
            <i class="fa-brands fa-linkedin text-2xl"></i>
            <span class="sr-only">LinkedIn</span>
        </a>
        <a
            href="https://x.com/Shrishesha4"
            target="_blank"
            rel="noopener noreferrer"
            class="text-neutral-700 transition hover:text-neutral-900 dark:text-neutral-300 dark:hover:text-neutral-100"
        >
            <i class="fa-brands fa-x-twitter text-2xl"></i>
            <span class="sr-only">Twitter</span>
        </a>
        <a
            href="mailto:shrisheshanarmatesshvara@gmail.com"
            target="_blank"
            class="text-neutral-700 transition hover:text-neutral-900 dark:text-neutral-300 dark:hover:text-neutral-100"
        >
            <i class="fa-regular fa-envelope text-2xl"></i>
            <span class="sr-only">Email</span>
        </a>
        <a 
            href="https://www.buymeacoffee.com/shrishesha4" 
            target="_blank"
            class="text-neutral-700 transition hover:text-neutral-900 dark:text-neutral-300 dark:hover:text-neutral-100"
        >
            <i class="fa fa-coffee text-2xl text-[#FFA500]"></i>
            <span class="sr-only">Buy me a coffee</span>
        </a>
    </div>
</div>

// 3d.space/src/components/ui/SocialLinks.tsx
"use client";

import { Github, Linkedin, Twitter, Mail, Coffee } from "lucide-react";
import { motion } from "framer-motion";

const socialLinks = [
  {
    name: "GitHub",
    url: "https://github.com/shrishesha4",
    icon: Github,
    color: "hover:text-neon-pink",
  },
  {
    name: "LinkedIn",
    url: "https://linkedin.com/in/shrishesha",
    icon: Linkedin,
    color: "hover:text-neon-blue",
  },
  {
    name: "Twitter",
    url: "https://x.com/Shrishesha4",
    icon: Twitter,
    color: "hover:text-neon-cyan",
  },
  {
    name: "Email",
    url: "mailto:shrisheshanarmatesshvara@gmail.com",
    icon: Mail,
    color: "hover:text-acid-green",
  },
  {
    name: "Buy Me a Coffee",
    url: "https://www.buymeacoffee.com/shrishesha4",
    icon: Coffee,
    color: "hover:text-yellow-400",
  },
];

export default function SocialLinks() {
  return (
    <div className="flex gap-6 justify-center items-center mt-8">
      {socialLinks.map((link, i) => (
        <motion.a
          key={link.name}
          href={link.url}
          target="_blank"
          rel="noopener noreferrer"
          className={`text-white/70 transition-colors duration-300 ${link.color}`}
          whileHover={{ scale: 1.2, rotate: 5 }}
          whileTap={{ scale: 0.9 }}
          initial={{ opacity: 0, y: 20 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ delay: i * 0.1 }}
        >
          <link.icon size={28} strokeWidth={1.5} />
          <span className="sr-only">{link.name}</span>
        </motion.a>
      ))}
    </div>
  );
}
