// 3d.space/src/app/blogs/page.tsx
"use client";

import { useState, useMemo } from "react";
import { motion } from "framer-motion";
import { usePortfolioData } from "@/hooks/usePortfolioData";
import BlogCard from "@/components/ui/BlogCard";
import GlitchText from "@/components/ui/GlitchText";
import { Search } from "lucide-react";

export default function BlogsPage() {
  const { blogs, loading } = usePortfolioData();
  const [searchQuery, setSearchQuery] = useState("");
  const [selectedTag, setSelectedTag] = useState<string | null>(null);

  const allTags = useMemo(() => {
    const tags = new Set<string>();
    blogs.forEach(blog => blog.tags?.forEach(tag => tags.add(tag)));
    return Array.from(tags);
  }, [blogs]);

  const filteredBlogs = useMemo(() => {
    return blogs.filter(blog => {
        const title = blog.title || "";
        const description = blog.description || "";
        
        const matchesSearch = 
            title.toLowerCase().includes(searchQuery.toLowerCase()) || 
            description.toLowerCase().includes(searchQuery.toLowerCase());
        const matchesTag = selectedTag ? blog.tags?.includes(selectedTag) : true;
        return matchesSearch && matchesTag;
    });
  }, [blogs, searchQuery, selectedTag]);

  return (
    <div className="min-h-screen pt-32 pb-20 px-4 max-w-7xl mx-auto">
        {/* Header */}
        <div className="mb-12 text-center">
            <GlitchText text="NEURAL_ARCHIVES" size="lg" className="font-bold mb-2" />
            <p className="text-neon-blue font-mono text-sm">// KNOWLEDGE_BASE_ACCESS</p>
        </div>

        {/* Search & Filter */}
        <div className="mb-12 flex flex-col md:flex-row gap-6 items-center justify-between bg-panel-bg border border-white/10 p-6 rounded-lg backdrop-blur-md">
            {/* Search Input */}
            <div className="relative w-full md:w-96">
                <Search className="absolute left-3 top-1/2 -translate-y-1/2 text-white/50 w-5 h-5" />
                <input 
                    type="text" 
                    placeholder="Search logs..." 
                    value={searchQuery}
                    onChange={(e) => setSearchQuery(e.target.value)}
                    className="w-full bg-darker-bg border border-white/10 rounded px-10 py-2 text-white focus:border-neon-pink focus:outline-none focus:box-glow transition-all font-mono"
                />
            </div>

            {/* Tags */}
            <div className="flex flex-wrap gap-2 justify-center">
                <button 
                    onClick={() => setSelectedTag(null)}
                    className={`px-3 py-1 rounded text-xs font-mono border transition-all ${!selectedTag ? 'bg-neon-blue/20 border-neon-blue text-white box-glow' : 'bg-transparent border-white/20 text-white/60 hover:border-white/50'}`}
                >
                    ALL
                </button>
                {allTags.map(tag => (
                    <button 
                        key={tag} 
                        onClick={() => setSelectedTag(tag === selectedTag ? null : tag)}
                        className={`px-3 py-1 rounded text-xs font-mono border transition-all ${selectedTag === tag ? 'bg-neon-pink/20 border-neon-pink text-white box-glow' : 'bg-transparent border-white/20 text-white/60 hover:border-white/50'}`}
                    >
                        {tag}
                    </button>
                ))}
            </div>
        </div>

        {/* Grid */}
        {loading ? (
             <div className="flex items-center justify-center h-64">
                <p className="font-mono text-neon-blue animate-pulse">DECRYPTING_DATA_STREAMS...</p>
            </div>
        ) : filteredBlogs.length > 0 ? (
            <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-8">
                {filteredBlogs.map((blog, i) => (
                    <BlogCard key={blog.id || i} blog={blog} index={i} />
                ))}
            </div>
        ) : (
            <div className="text-center py-20 border border-dashed border-white/10 rounded-lg">
                <p className="text-white/50 font-mono">NO_RECORDS_FOUND</p>
            </div>
        )}
    </div>
  );
}

// sv/src/routes/blogs/+page.svelte
<script lang="ts">
    import { onMount } from 'svelte';
    import { get } from 'svelte/store';
    import { blogs } from '$lib/stores/blogs';
    import BlogViewer from '$lib/components/BlogViewer.svelte';

    let searchQuery = $state('');
    let selectedFilter = $state('all');
    let showFilterDropdown = $state(false);
    let availableTags: { name: string; count: number }[] = $state([]);

    onMount(async () => {
        await blogs.load();
        const current = (get(blogs) || []) as Array<{ tags?: string[] }>;
        const allTags = current.flatMap(blog => blog.tags || []);
        const tagCount = new Map<string, number>();
        allTags.forEach(tag => {
            tagCount.set(tag, (tagCount.get(tag) || 0) + 1);
        });
        availableTags = Array.from(tagCount.entries())
            .map(([name, count]) => ({ name, count }))
            .sort((a, b) => b.count - a.count);
    });
</script>

<div class="min-h-screen p-4 md:p-8">
    <div class="max-w-7xl mx-auto">
    <div class="flex flex-col md:flex-row md:items-center justify-between gap-6 mb-10 md:mb-12">
    
        <h1 class="text-4xl font-bold tracking-tight">Blogs</h1>
        <!-- Search and Filter Section -->
        <div class="flex items-center gap-3 flex-1 max-w-xl md:justify-end">
            <!-- Search Input -->
            <div class="relative flex-1 max-w-sm">
                <input
                type="text"
                bind:value={searchQuery}
                placeholder="Search posts..."
                class="w-full px-5 py-3 pl-11 rounded-2xl bg-neutral-100/80 dark:bg-white/5 border border-neutral-300 dark:border-white/10 text-neutral-900 dark:text-white placeholder-neutral-500 dark:placeholder-neutral-400 focus:outline-none focus:ring-2 focus:ring-primary-500/50 transition-all backdrop-blur-sm"
                />
                <i class="fas fa-search absolute left-4 top-1/2 -translate-y-1/2 text-neutral-500 dark:text-neutral-400"></i>
                {#if searchQuery}
                <!-- svelte-ignore a11y_consider_explicit_label -->
                <button
                onclick={() => searchQuery = ''}
                class="absolute right-4 top-1/2 -translate-y-1/2 text-neutral-500 hover:text-neutral-700 dark:text-neutral-400 dark:hover:text-neutral-200"
                aria-label="Clear search"
                >
                <i class="fas fa-times"></i>
            </button>
            {/if}
        </div>
        
        <!-- Filter Dropdown -->
        <div class="relative">
            <button
            onclick={() => showFilterDropdown = !showFilterDropdown}
            class="px-5 py-3 rounded-2xl bg-neutral-100/80 dark:bg-white/5 border border-neutral-300 dark:border-white/10 text-neutral-900 dark:text-white hover:bg-neutral-200/80 dark:hover:bg-white/10 transition-all backdrop-blur-sm flex items-center gap-2 whitespace-nowrap"
            >
            <i class="fas fa-filter text-neutral-500 dark:text-neutral-400"></i>
            <span class="hidden md:inline font-medium">{selectedFilter === 'all' ? 'All' : selectedFilter}</span>
            <i class="fas fa-chevron-down text-xs text-neutral-500 dark:text-neutral-400 ml-1"></i>
        </button>
        
        {#if showFilterDropdown}
        <div class="absolute right-0 mt-2 w-64 rounded-2xl bg-white dark:bg-neutral-900 border border-neutral-100 dark:border-neutral-800 shadow-xl z-50 backdrop-blur-md overflow-hidden">
            <div class="p-2">
                <button
                onclick={() => { selectedFilter = 'all'; showFilterDropdown = false; }}
                class={"w-full text-left px-3 py-2 rounded-md hover:bg-neutral-100 dark:hover:bg-neutral-700 text-neutral-900 dark:text-white transition-colors " + (selectedFilter === 'all' ? 'bg-primary-100 dark:bg-primary-900' : '')}
                >
                <span class="font-medium">All Posts</span>
            </button>
            {#if availableTags.length > 0}
            <div class="border-t border-neutral-200 dark:border-neutral-700 my-2"></div>
            <div class="text-xs font-semibold text-neutral-500 dark:text-neutral-400 px-3 py-1">Tags</div>
            {#each availableTags as tag}
            <button
            onclick={() => { selectedFilter = tag.name; showFilterDropdown = false; }}
            class={"w-full text-left px-3 py-2 rounded-md hover:bg-neutral-100 dark:hover:bg-neutral-700 text-neutral-900 dark:text-white transition-colors text-sm " + (selectedFilter === tag.name ? 'bg-primary-100 dark:bg-primary-900' : '')}
            >
            <div class="flex items-center justify-between">
                <span>{tag.name}</span>
                <span class="text-xs text-neutral-500 dark:text-neutral-400 bg-neutral-100 dark:bg-neutral-700 px-2 py-0.5 rounded-full">{tag.count}</span>
            </div>
        </button>
        {/each}
        {/if}
    </div>
</div>
{/if}
</div>
</div>

</div>
<BlogViewer bind:searchQuery bind:selectedFilter />
    </div>
</div>

<!-- Click outside to close dropdown -->
<svelte:window onclick={(e: Event) => {
    const target = (e.target as HTMLElement) || null;
    if (!target || !target.closest('.relative')) {
        showFilterDropdown = false;
    }
}} />
