// src/routes/blogs/[slug]/+page.svelte
<script lang="ts">
    import { blogs } from '$lib/stores/blogs';
    import { page } from '$app/stores';
    import { onMount } from 'svelte';
    import LoadingSpinner from '$lib/components/LoadingSpinner.svelte';

    let currentBlog: typeof $blogs[0] | undefined;
    let loading = true;
    let readerMode = false;

    onMount(async () => {
        try {
            await blogs.load();
            currentBlog = $blogs.find(blog => blog.slug === $page.params.slug);
        } finally {
            loading = false;
        }
    });

    function toggleReaderMode() {
        readerMode = !readerMode;
    }
</script>

{#if loading}
    <LoadingSpinner />
{:else if currentBlog}
    <article class="pt-0 p-4 md:pt-0 md:p-8 transition-all duration-500 ease-in-out">
        <div class="{readerMode ? 'max-w-2xl' : 'max-w-7xl'} mx-auto transition-all duration-500 ease-in-out">
            <div class="flex items-center justify-between mb-8">
                <a href="/blogs" class="inline-flex items-center text-neutral-600 dark:text-neutral-400 hover:text-neutral-900 dark:hover:text-neutral-100 transition-colors">
                    <i class="fas fa-chevron-left mr-2"></i>
                    Posts
                </a>
                
                <!-- svelte-ignore a11y_consider_explicit_label -->
                <button 
                    on:click={toggleReaderMode}
                    class="p-2 rounded-full hover:bg-neutral-100 dark:hover:bg-neutral-800 transition-colors text-neutral-600 dark:text-neutral-400"
                    title={readerMode ? "Exit Reader Mode" : "Enter Reader Mode"}
                >
                    <i class="fas {readerMode ? 'fa-book-open' : 'fa-book'} text-xl"></i>
                </button>
            </div>

            <header class="mb-8 {readerMode ? 'text-center' : ''}">
                <h1 class="text-4xl md:text-5xl font-bold mb-6 leading-tight {readerMode ? 'text-neutral-900 dark:text-neutral-100' : ''}">
                    {currentBlog.title}
                </h1>
                <div class="flex items-center {readerMode ? 'justify-center' : 'justify-between'} gap-4 text-sm text-neutral-500 dark:text-neutral-400">
                    <div class="flex flex-wrap gap-2 items-center">
                        {#if !readerMode}
                            {#each currentBlog.tags as tag}
                                <span class="px-3 py-1 glass-button dark:bg-neutral-800 rounded-full text-sm flex-shrink-0">
                                    {tag}
                                </span>
                            {/each}
                        {/if}
                    </div>
                    <time class="flex-shrink-0 font-medium">
                        {new Date(currentBlog.date).toLocaleDateString(undefined, { year: 'numeric', month: 'long', day: 'numeric' })}
                    </time>
                </div>
            </header>

            {#if currentBlog.image && !readerMode}
                <div class="w-full md:h-[500px] overflow-hidden rounded-2xl mb-12 shadow-2xl">
                    <img 
                        src={currentBlog.image} 
                        alt={currentBlog.title}
                        class="w-full h-full object-cover transform hover:scale-105 transition-transform duration-700"
                    />
                </div>
            {/if}

            <div class="prose dark:prose-invert max-w-none {readerMode ? 'prose-lg md:prose-xl leading-relaxed' : 'prose-lg'} marker:text-primary-500">
                {@html currentBlog.content}
            </div>
        </div>
    </article>
{:else}
    <div class="min-h-screen flex items-center justify-center">
        <p class="text-neutral-600 dark:text-neutral-400 text-xl">Blog post not found</p>
    </div>
{/if}

<style>
    /* Add smooth transitions for layout changes */
    :global(html) {
        scroll-behavior: smooth;
    }
</style>

// nxt/src/app/blogs/[slug]/page.tsx
import { notFound } from "next/navigation";
import Image from "next/image";
import Link from "next/link";
import { ChevronLeft } from "lucide-react";
import { getBlogBySlug, getBlogs } from "@/lib/data/blogs";
import { Badge } from "@/components/ui/badge";
import { BlogContent } from "@/components/blogs/blog-content";
import { optimizeImage } from "@/lib/image-optimizer";

export const revalidate = 300;

export async function generateStaticParams() {
  const blogs = await getBlogs();
  return blogs.map((b) => ({ slug: b.slug }));
}

export default async function BlogPostPage({ params }: { params: Promise<{ slug: string }> }) {
  const { slug } = await params;
  const blog = await getBlogBySlug(slug);
  if (!blog) notFound();

  return (
    <article className="mx-auto max-w-3xl px-4 py-12 md:py-20">
      <Link href="/blogs" className="mb-8 inline-flex items-center text-sm text-muted-foreground transition-colors hover:text-foreground">
        <ChevronLeft className="mr-1 size-4" />
        Posts
      </Link>

      <header className="mb-10">
        <h1 className="mb-4 text-4xl font-bold leading-tight tracking-tight md:text-5xl">{blog.title}</h1>
        <div className="flex flex-wrap items-center gap-3 text-sm text-muted-foreground">
          <time>
            {new Date(blog.date).toLocaleDateString(undefined, { year: "numeric", month: "long", day: "numeric" })}
          </time>
          {blog.tags.map((tag) => (
            <Badge key={tag} variant="secondary">{tag}</Badge>
          ))}
        </div>
      </header>

      {blog.image && (
        <div className="relative mb-12 aspect-video w-full overflow-hidden rounded-2xl shadow-2xl">
          <Image src={optimizeImage(blog.image, { width: 1200 })} alt={blog.title} fill className="object-cover" sizes="768px" priority />
        </div>
      )}

      <BlogContent content={blog.content} />
    </article>
  );
}
